### ISSUE TITLE
TODO liste

### ISSUE THREAD

**Issue by Lecrapouille** [Lecrapouille/Ecstasy#1]
- [x] Profiling: ntdll.dll is consuming 90% of resources
- [x] Ajouter l'axe X et Y dans le readme pour les blocks de la ville. Traduire les noms des fichiers.
- [ ] Utiliser un frustum culling en 2D au lieu de 3D
- [ ] Donner un nom aux litteraux Camera.Id et utiliser un type pour les noms. Idem pour l'etat des feux rouges.
- [ ] Init le volant a 0
- [ ] Gerer correctement la liberation des ressources OpenGL (textures, liste d'affichage, texture dans les fichiers ASE).
- [ ] Appliquer correctement le pas de temps dans les equations et les touches du clavier.
- [x] Corriger la tempo des feux rouges.
- [x] Corriger le bug les voitures qui grillent le feu rouge.
- [ ] Ajouter random dans la distance de securite des voitures.
- [x] Afficher les feux arrières des voitures.
- [ ] Mettre plus d'aleatoire dans la position des voitures
- [ ] Ne pas calculer la dynamique pour les voitures non affichees. Utiliser une equation simplifiee pour les voitures IA.
- [ ] Corriger les coefs de la dynamique de certaines voitures. Contraindre la position des roues et de la carcasse (sol, compression, extension)
- [x] Finir le terrain "off road" (corriger le gradient).
- [x] Corriger la fonction altitude des terrains et ne pas faire tomber la voiture quand elle passe dans les maisons.
- [ ] Ajouter un effet ressort lors de la collision avec les maisons. Et decaller la detection (apres le trottoir)
- [x] Ajouter un trottoir.
- [ ] Elevation du trottoir.
- [x] Ajouter un random sur la hauteur immeubles.
- [ ] Les immeubles  ne collent pas toujours au sol quand la pente de la route est grande.
- [x] ESPACE_CAREFOUR ne modifie pas la position des voitures. (partiellement fait: maintenant la taille de la ville est ok).
- [x] Modifier le facteur d'echelle des feux rouges et les placer avant/apres le feu.
- [x] les voitures ne sont pas affichees si on est sur les coins du tore.
- [x] bug de modulo des quartiers (affichage noir)
- [x] Textures: supprimer les textures inutiles et les deplacer dans les dossiers voitures.
- [x] Des textures des voitures sont plusieurs fois chargees plusieurs fois
- [ ] Des textures ayant des chemins differents peuvent etre chargees en doubles.
- [x] Bug trottoir et terrain sont utilises en meme temps.
- [ ] Segfault quand la camera de la voiture est trop eloignee.
- [ ] Deplacer la camera en hauteur
- [ ] Scintillement des textures

**Comment by Lecrapouille** [comment]
Régression(s):
- [ ] Il manque une roue (pas chargée) et est remplacée par une particule (du plus joli effet)
- [x] Si on relance une nouvelle partie le chargement reste bloqué

**Comment by Lecrapouille** [comment]
Scheduled tasks order:
- [x] Fix bugs in traffic jam (cars passing on red signal). Add more random in the traffic.

- [x] Fix bug in displaying traffic jam on city corners.

- [ ] Fix step time in physic. Make the simulation numerically stable.

- [ ] Remove magic numbers (acceleration, ...) for player inputs and move them in the configuration file for each cars. Fix wheel rotation. Add rear lights position in the config file. Apply them for the traffic jam. Missing desired velocity for cars, they instantly apply the desired velocity.

- [ ] Give to the cars the ability to turn just on right.

- [ ] Improve car dynamic (constrain wheel Z position, add air friction, ground friction, fix gravity, add force depending on the angle of the road, Archimedes and flow force on the river, fix inertia, add pumping effect, let move the car if driving wheels is touching the ground.

- [ ] Compress textures, add mipmaps, improve frustum culling for removing unseen blocks.

- [ ] Add collisions.

- [ ] Add police cars and add red and blue flare effects.
